general {
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
    immediate_render = true
}

animations {
  enabled: false
}

background {
    monitor =
    color = rgb(0, 0, 0) 
    blur_passes = 2
    blur_size = 2
    noise = 0.1
    contrast = 1 
    brightness = 1 
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

input-field {
    monitor =
    size = 400, 50
    dots_size = 2
    dots_rounding = -1
    outline_thickness = 0;
    dots_size = 0.25
    dots_spacing = 0.55
    dots_center = true
    inner_color = rgb(0, 0, 0)
    outer_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    check_color = rgb(0, 0, 0)
    fade_on_empty = false
    placeholder_text =  
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fail_transition = 100 
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 6%, 9.5%
    halign = left
    valign = center
}


label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%k:%M")"
  color = rgba(255, 255, 255, 0.8)
  font_size = 90
  font_family = Times New Roman MT Condensed Bold
  position = 0, 88%
  halign = left
  valign = left
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date '+%B %eXX' | sed -e 's/11XX/11th/' -e 's/12XX/12th/' -e 's/13XX/13th/' -e 's/1XX/1st/' -e 's/2XX/2nd/' -e 's/3XX/3rd/' -e 's/XX/th/')"
  color = rgba(255, 255, 255, 0.8)
  font_size = 90
  font_family = Times New Roman MT Condensed Bold
  position = 0, 79%
  halign = left
  valign = left
}

label {
  monitor =
  text = Password: 
  color = rgba(255, 255, 255, 0.8)
  font_size = 50
  font_family = Times New Roman MT Condensed Bold
  position = 0, 10%
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:0] echo "Episode: $(( $RANDOM % 26 ))"
  color = rgba(255, 255, 255, 0.8)
  font_size = 50
  font_family = Times New Roman MT Condensed Bold
  position = 0, 15%
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:0] echo "$(whoami)"
  color = rgba(255, 255, 255, 0.8)
  font_size = 80
  font_family = Times New Roman MT Condensed Bold
  position = -5%, 5%
  halign = right
  valign = right
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A")"
  color = rgba(255, 255, 255, 0.8)
  font_size = 110
  font_family = Times New Roman MT Condensed Bold
  position = 0, 68%
  halign = left
  valign = left
}