# Core
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = swww-daemon --format xrgb
exec-once = fcitx5
exec-once = hypridle
exec-once = swaync
exec-once = hyprsunset --temperature 5000
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# First workspace
exec-once = [workspace 1] alacritty
exec-once = [workspace 1] sleep 0.5 && alacritty -e peaclock
exec-once = [workspace 1] sleep 1 && alacritty -e btm


# Second workspace
exec-once = [workspace 2 silent] discord
exec-once = [workspace 2 silent] zen-browser
