# Core
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = awww-daemon --format xrgb
exec-once = fcitx5
exec-once = hypridle
exec-once = swaync
exec-once = hyprsunset --temperature 5000
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# First workspace
exec-once = [workspace 1] alacritty

exec-once = [workspace 1] sleep 0.5 && \
  hyprctl dispatch layoutmsg "preselect r" && \
  alacritty -e btm

exec-once = [workspace 1] sleep 1.0 && \
  hyprctl dispatch layoutmsg "preselect u" && \
  alacritty -e peaclock

exec-once = [workspace 1] sleep 1.5 && \
  hyprctl dispatch layoutmsg "preselect r" && \
  alacritty -e cava


# Second workspace
exec-once = [workspace 2 silent] discord
exec-once = [workspace 2 silent] zen-browser
